### ISSUE TITLE
Error on npm run start-ssr:prod

### ISSUE THREAD

**Issue by bresson** [anorudes/redux-easy-boilerplate#86]
Any ideas for the following error in "npm run start-ssr:prod" on my machine?

```
npm run start-ssr:prod

> redux-easy-boilerplate@3.1.0 start-ssr:prod /Users/jessebraddock/Copy/_projects/_experiments/redux-easy-boilerplate
> NODE_ENV=production node bin/server-ssr.js

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:1008:11)
    at exports._exceptionWithHostPort (util.js:1031:20)
    at Server._listen2 (net.js:1240:19)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1385:5)
    at EventEmitter.listen (/Users/.../redux-easy-boilerplate/node_modules/express/lib/application.js:617:24)
    at Object.<anonymous> (server-ssr.js:136:5)
    at Module._compile (module.js:541:32)
    at loader (/Users/jessebraddock/Copy/_projects/_experiments/redux-easy-boilerplate/node_modules/babel-register/lib/node.js:148:5)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/.../redux-easy-boilerplate/node_modules/babel-register/lib/node.js:158:7)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/.../redux-easy-boilerplate/bin/server-ssr.js:29:1)

npm ERR! Darwin 15.6.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start-ssr:prod"
npm ERR! node v6.3.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! redux-easy-boilerplate@3.1.0 start-ssr:prod: `NODE_ENV=production node bin/server-ssr.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the redux-easy-boilerplate@3.1.0 start-ssr:prod script 'NODE_ENV=production node bin/server-ssr.js'.
```

**Comment by maxgram** [comment]
80 is a default port on your machine. there is something already running on it.
if you open localhost:80 on Mac you'll see "It works!" from apache

**Comment by bresson** [comment]
OK it works fine once I changed the port. Thanks.
